# Generated by Django 6.0.6 on 2026-07-03 20:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Название товара')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='details', serialize=False, to='store.product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.IntegerField(default=0, verbose_name='Остаток на складе')),
            ],
        ),
    ]
