# Generated by Django 6.0.6 on 2026-07-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='products_name',
            new_name='name',
        ),
    ]
