# Generated by Django 6.0.6 on 2026-07-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='can_access_dashboard',
            field=models.BooleanField(default=False, verbose_name='Доступ к панели редактора'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='can_delete_products',
            field=models.BooleanField(default=False, verbose_name='Разрешено удалять товары'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='can_manage_orders',
            field=models.BooleanField(default=False, verbose_name='Разрешено управлять заказами'),
        ),
    ]
