# Generated by Django 6.0.6 on 2026-07-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_adminprofile_tagproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_checked',
            field=models.BooleanField(default=True, verbose_name='Выбран для покупки'),
        ),
    ]
