# Generated by Django 6.0.6 on 2026-07-05 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_alter_product_options_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
